// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/calculate-turnover-cost.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var DEFAULT_REPLACEMENT_COST_MULTIPLIER = 0.25;
var calculate_turnover_cost_default = defineTool({
  name: "calculate_turnover_cost",
  title: "Calculate dealership turnover cost",
  description: "Estimate the annual cost of employee turnover at a dealership using the same math as the WerkandMe ROI calculator. Provide team size, average salary, and either annual turnover rate (%) or monthly hires; optionally override replacement cost per employee.",
  inputSchema: {
    employees: z.number().int().min(1).max(5e3).describe("Total team members at the dealership."),
    avgSalary: z.number().min(1e4).max(5e5).describe("Average annual salary in USD."),
    turnoverRate: z.number().min(0).max(200).optional().describe("Annual turnover rate as a percent (e.g. 45 for 45%). Provide this OR monthlyHires."),
    monthlyHires: z.number().min(0).max(100).optional().describe("Number of hires per month. Provide this OR turnoverRate."),
    customReplacementCost: z.number().min(0).max(5e5).optional().describe("Optional: your actual cost to hire + train + ramp one employee (USD). Defaults to 25% of avgSalary."),
    improvementRate: z.number().min(0).max(100).optional().describe("Optional: expected % reduction in turnover from WerkandMe (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ employees, avgSalary, turnoverRate, monthlyHires, customReplacementCost, improvementRate }) => {
    if (turnoverRate === void 0 && monthlyHires === void 0) {
      return {
        content: [{ type: "text", text: "Provide either turnoverRate or monthlyHires." }],
        isError: true
      };
    }
    const employeesLost = monthlyHires !== void 0 ? monthlyHires * 12 : Math.round(employees * ((turnoverRate ?? 0) / 100));
    const effectiveTurnoverRate = monthlyHires !== void 0 ? Math.round(monthlyHires * 12 / employees * 100) : turnoverRate ?? 0;
    const replacementCostPerEmployee = customReplacementCost ?? avgSalary * DEFAULT_REPLACEMENT_COST_MULTIPLIER;
    const annualTurnoverCost = employeesLost * replacementCostPerEmployee;
    const improvement = improvementRate ?? 30;
    const potentialSavings = Math.round(annualTurnoverCost * (improvement / 100));
    const fmt = (n) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
    const summary = `Dealership turnover cost estimate
- Employees lost/year: ${employeesLost} (effective turnover ${effectiveTurnoverRate}%)
- Replacement cost/employee: ${fmt(replacementCostPerEmployee)}${customReplacementCost === void 0 ? " (25% of salary, conservative)" : " (custom)"}
- Annual turnover cost: ${fmt(annualTurnoverCost)}
- Potential savings with WerkandMe (${improvement}% improvement): ${fmt(potentialSavings)}/yr`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        employeesLost,
        effectiveTurnoverRate,
        replacementCostPerEmployee: Math.round(replacementCostPerEmployee),
        annualTurnoverCost: Math.round(annualTurnoverCost),
        improvementRate: improvement,
        potentialSavings,
        currency: "USD"
      }
    };
  }
});

// src/lib/mcp/tools/get-pitch-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SUMMARY = `WerkandMe \u2014 Employee engagement platform built for auto dealerships.

The problem: Dealership turnover runs 40-80%/yr. Every departure costs 25-200% of salary in hiring, training, and ramp time. Disengagement shows up as lost sales, missed CSI scores, and constant re-staffing.

The platform:
- Emotional Check-Ins \u2014 catch disengagement before resignation
- Manager Dashboard \u2014 real-time, actionable team health
- Smart Gamification \u2014 challenges that drive sales, service, and CSI
- Personalized Recognition \u2014 tailored to individual motivators
- Meaningful Rewards \u2014 incentives that actually matter
- Real-Time Analytics \u2014 visibility into team health
- Dedicated Culture Coach \u2014 a real person supporting the dealership, running the playbook, keeping engagement sticky

Why it's different: Mobile-first, built BY dealership people FOR dealership people. Fractional Culture Coach is part of your Culture Team, not a vendor at arm's length.

Implementation: 4-week white-glove onboarding.

Full deck: https://meetwerk.lovable.app
Standalone turnover ROI calculator: https://meetwerk.lovable.app/calculator`;
var get_pitch_summary_default = defineTool2({
  name: "get_pitch_summary",
  title: "Get WerkandMe pitch summary",
  description: "Return a concise summary of the WerkandMe pitch: problem, platform features, Culture Coach, and links to the full deck and ROI calculator. Use this to brief a user on what WerkandMe does.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: SUMMARY }],
    structuredContent: {
      deckUrl: "https://meetwerk.lovable.app",
      calculatorUrl: "https://meetwerk.lovable.app/calculator"
    }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "werkandme-mcp",
  title: "WerkandMe",
  version: "0.1.0",
  instructions: "Tools for the WerkandMe dealership engagement pitch. Use `get_pitch_summary` to brief the user on what WerkandMe does, and `calculate_turnover_cost` to run the ROI calculator with a dealership's numbers.",
  tools: [calculate_turnover_cost_default, get_pitch_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
